### ISSUE TITLE
Hacer tablero de vision del producto

### ISSUE THREAD

**Issue by Anderhposada** [Problemas-Ambientales/EQUIPO3_RU_PPI2020#5]

**Comment by marthaduque** [comment]
REVISARLA VS EL DOCUMENTO DE LA SEMANA 2 DE IR.

**Comment by marthaduque** [comment]
La visión debe seguir la estructura solicitada en el documento de la semana 2 de IR. y el tablero en la parte de carcteristicas del producto debe ser coherente con el alcance aprobado del proyecto:"Aplicación movil orientado a indicar de acuerdo al elemento que se va a desechar cuanto es el tiempo de biodegradación y que consecuencias genera al medio ambiente "
